=== st-001/json-schema-to-deno-ts-util/metaSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "MetaSchema",
  "description": "Meta-Schema for validating schemas",
  "type": "object",
  "properties": {
    "$id": {
      "type": "string"
    },
    "$schema": {
      "type": "string"
    },
    "type": {
      "type": "string",
      "enum": ["object"]
    },
    "description": {
      "type": "string"
    },
    "properties": {
      "type": "object",
      "patternProperties": {
        ".*": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": ["string", "number", "array"]
            },
            "description": {
              "type": "string"
            },
            "default": {
              "type": ["string", "number", "array"]
            },
            "enum": {
              "type": "array",
              "items": {
                "type": ["string", "number"]
              }
            },
            "minimum": {
              "type": "number"
            }
          },
          "required": ["type", "description", "default"],
          "additionalProperties": false
        }
      }
    },
    "required": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "required": ["$id", "type", "description", "properties", "required"],
  "additionalProperties": false
}

=== st-001/json-schema-to-deno-ts-util/schemas/Example/schema.json
{
  "$id": "Example",
  "type": "object",
  "description": "A example schema with all allowed scenarios.",
  "properties": {
    "randomNumber": {
      "type": "number",
      "description": "A random number",
      "enum": [
        1,
        2,
        3
      ],
      "default": 0
    },
    "randomWord": {
      "type": "string",
      "description": "A random word",
      "enum": [
        "foo",
        "bar",
        "baz"
      ],
      "default": "foo"
    },
    "word": {
      "type": "string",
      "description": "A word",
      "default": "foo"
    },
    "number": {
      "type": "number",
      "description": "A number",
      "default": 0
    }
  },
  "required": [
    "randomNumber"
  ]
}

=== st-001/json-schema-to-deno-ts-util/schemas/Customer/schema.json
{
  "$id": "Customer",
  "type": "object",
  "description": "A customer.",
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the customer.",
      "default": ""
    },
    "address": {
      "type": "string",
      "description": "The address of the customer.",
      "default": ""
    },
    "phone": {
      "type": "string",
      "description": "The phone number of the customer.",
      "default": ""
    },
    "email": {
      "type": "string",
      "description": "The email address of the customer.",
      "default": ""
    }
  },
  "required": [
    "name",
    "address",
    "phone",
    "email"
  ]
}

=== st-001/json-schema-to-deno-ts-util/schemas/PizzaOrderItem/schema.json
{
  "$id": "PizzaOrderItem",
  "type": "object",
  "description": "You have requested data which matches this JSON schema. You will be provided with their response in the form of natural language (email, text message, chat bot, etc). You need to analyse it and then parse it into this schema. Your output needs to be a one line JSON schema array that contains objects which match this schema. Your output must be parsable and must validate against this schema. There can be multiple objects. If you are unable to parse the message, output an array containing an object with the default values.",
  "properties": {
    "size": {
      "type": "string",
      "description": "The size of the pizza.",
      "enum": ["small", "medium", "large"],
      "default": "medium"
    },
    "sauce": {
      "type": "string",
      "description": "The type of sauce on the pizza.",
      "enum": ["tomato", "white", "bbq"],
      "default": "tomato"
    },
    "toppings": {
      "type": "array",
      "description": "The list of toppings on the pizza.",
      "items": {
        "type": "string"
      },
      "default": []
    },
    "quantity": {
      "type": "number",
      "description": "The quantity of the pizza.",
      "default": 1,
      "minimum": 1
    },
    "instructions": {
      "type": "string",
      "description": "Special instructions for the pizza.",
      "default": "null"
    }
  },
  "required": [
    "size",
    "sauce",
    "toppings",
    "quantity",
    "instructions"
  ]
}

=== st-001/json-schema-to-deno-ts-util/schemas/Task/schema.json
{
  "$id": "Task",
  "type": "object",
  "description": "A task",
  "properties": {
    "task": {
      "type": "string",
      "description": "The task name",
      "enum": [
        "sendEmail",
        "sendTeamsMessage",
        "scheduleMeeting",
        "getCustomer",
        "getEmployee",
        "sendWhatsAppMessage"
      ],
      "default": ""
    },
    "taskDetails": {
      "type": "string",
      "description": "All details required to complete the task",
      "default": ""
    }
  },
  "required": [
    "task",
    "taskDetails"
  ]
}
